### ISSUE TITLE
Support for guild scheduled events.

### ISSUE THREAD

**Issue by nerdguyahmad** [diskord-dev/diskord#26]
This issue tracks the TODOs for guild scheduled events.

- [x] [API typings](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-guild-scheduled-event-structure)
- [x] Gateway events
  - [x] [Guild Scheduled Event Create](https://discord.com/developers/docs/topics/gateway#guild-scheduled-event-create)
  - [x] [Guild Scheduled Event Update](https://discord.com/developers/docs/topics/gateway#guild-scheduled-event-update)
  - [x] [Guild Scheduled Event Delete](https://discord.com/developers/docs/topics/gateway#guild-scheduled-event-delete)
  - [x] ~~[Guild Scheduled Event User Add](https://discord.com/developers/docs/topics/gateway#guild-scheduled-event-user-add)~~ \*
  - [x] ~~[Guild Scheduled Event User Remove](https://discord.com/developers/docs/topics/gateway#guild-scheduled-event-user-remove)~~ \*
- [x] Endpoints
  - [x] [List Scheduled Events for Guild](https://discord.com/developers/docs/resources/guild-scheduled-event#list-scheduled-events-for-guild)
  - [x] [Create Guild Scheduled Event](https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event)
  - [x] [Get Guild Scheduled Event](https://discord.com/developers/docs/resources/guild-scheduled-event#get-guild-scheduled-event)
  - [x] [Modify Guild Scheduled Event](https://discord.com/developers/docs/resources/guild-scheduled-event#modify-guild-scheduled-event)
  - [x] [Delete Guild Scheduled Event](https://discord.com/developers/docs/resources/guild-scheduled-event#delete-guild-scheduled-event)
  - [x] [Get Guild Scheduled Event Users](https://discord.com/developers/docs/resources/guild-scheduled-event#get-guild-scheduled-event-users)

Feel free to contribute.

\* user events are experimental and won't be implemented yet in stable.

Note: All contributions must point towards `core/events` branch

**Comment by FlamptX** [comment]
I would contribute but I'm not sure where and how it should be made..
