### ISSUE TITLE
SlashCommands object is not callable

### ISSUE THREAD

**Issue by dylanc24** [diskord-dev/diskord#27]
### Summary

Just an error in pycharm with the lib 

### Reproduction Steps

```py
import diskord
from diskord.ext import commands
bot = commands.Bot(command_prefix='!', application_command_guild_ids=834489585118740530)


@bot.event
async def on_ready():
    print('ready')


@bot.slash_command()
@diskord.application.option('text', description='The text to say!')
async def say(ctx, text):
    await ctx.respond(f'{ctx.author.name} said: {text}')

bot.run("")

```

Using this code in PyCharm (from example but same result with my own code)

### Expected Results

0 error

### Actual Results

Actually, i'm having this error "Object is not callable" for the SlashCommands object but when i run the code eveything is fine it's juste annoying that having 34 error but it's only like "fake error"

### Intents

32767

### System Information

- Python v3.9.7-final
- diskord v2.6.1-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22494

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by MarzaElise** [comment]
its not *really* an error but rather a type-hint bug since the code works fine

**Comment by dylanc24** [comment]
> its not _really_ an error but rather a type-hint bug since the code works fine

Yes, it's true I misspoke.

**Comment by nerdguyahmad** [comment]
Thanks for bringing this up. This is currently one of the top priority for next release as application commands are not well typed and I would work on fixing this soon.

**Comment by nerdguyahmad** [comment]
I have fixed a few major issues with this and the rest minor ones would be addressed later. Thanks.
